<?php if($block->checkLogin() == 1 ): ?>
<?php $noti=$this->getNotification()?>
<div class="dropdown">
<button onclick="myFunction()" class="dropbtn"><?php echo count($noti); ?> Nofitication(s)</button>
  <div id="myDropdown" class="dropdown-content">
    <?php foreach ($noti as $item ) { ?>
         <a><?php echo $item->getContent(); ?></a>
    <?php } ?>
  </div>
</div>

<script>
/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}
// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>
<?php endif; ?>