<form class="form" id="comment-form" action="><?php echo $block->getFormAction(); ?>" method="post">

    <fieldset class="fieldset">
        <legend class="legend"><span><?php  echo __('Add new comment') ?></span></legend><br>
        <div class="note"></div>
        <div class="field required">
            <label for="user_id" class="label">
                <span><?php echo __('ID') ?></span>
            </label>
            <div class="control">
                <input type="text" id="user_id" name="author" class="input-text" width="50%">
            </div>
        </div>
        <div class="field required">
            <label for="comment" class="label">
                <span><?php echo __('Content') ?></span>
            </label>
            <div class="control">
                <textarea id="comment" name="content" class="input-text"></textarea>
            </div>
        </div>
        <div class="field required">
            <label for="email" class="label">
                <span><?php echo __('Email') ?></span>
            </label>
            <div class="control">
                <input type="email" name="email" class="input-text" id="email">
            </div>
        </div>
    </fieldset>
    <input type="hidden" name="post_id" value="<?php echo $block->getPostID() ?>"/>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="submit" id ="submit" class="action submit primary" value="<?php  echo __('Submit') ?>">
        </div>
        <input type="hidden" name="post_id" value="<?php echo $block->getPostId() ?>"/>
        <input type="hidden" name="user_id" value="<?php echo $block->getUserId() ?>"/>
    </div>
</form>
<?php
$ajaxurl = $block->getFormAction();
?>
<script type="text/x-magento-init">
       {
            "*": {
               "OpenTechiz_Blog/js/commentajax": {
                    "AjaxUrl": "<?php echo $ajaxurl; ?>"
               }
            }
        }
</script>